name: MineCordLiveChat
main: com.lith.minecordlivechat.LiveChatPlugin

version: 0.0.1
api-version: 1.20

description: A MineCraft x Discord live chat integration plugin
author: Lith
website: https://github.com/ImLith/MC-MineCord-LiveChat

depend: [LithCore, MineCord]
softdepend: [Emojies]

commands:
  lcReload:
    description: Reload configs
    usage: /<command>
    permission: livechat.reload

permissions:
  livechat.reload:
    description: Use the /lcReload command
    default: op
